name: Check AWS Access

on: 
  push:
    branches: 
      - main

jobs:
 check-access:
   runs-on: ubuntu-latest

   steps:

   - name: Checkout code
     uses: action/checkout@v3

   - name: Configure AWS credentials
   - uses: aws-action/configure-aws-credential@v2
     with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: 'us=east-2'

   - name: Verify AWS credentials
     run: aws sts get-caller-identity



