name: Check AWS Access

on: 
  push:
    branches: 
      - main

jobs:
  check-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Correct action to checkout code

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2  # Correct action to configure AWS credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-2'  # Correct AWS region

    - name: Verify AWS credentials
      run: aws sts get-caller-identity  # Verifies that the credentials are working
