[theme]
primaryColor = "#fffd7b"
backgroundColor = "#000000"  # Set background to black
secondaryBackgroundColor = "#1e1e1e"  # Dark gray for sidebar background
textColor = "#ffffff"  # White text
font = "sans serif"
